version: '1'

services:
#  apka:
#    image: projekt
#    container_name: apka
#    networks:
#      - kasia
  cassandra:
    container_name: cassandra
    image: 'bitnami/cassandra:latest'
    networks:
      kasia:
        ipv4_address: 172.20.0.2 #static ip

networks:
  kasia:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/24
          gateway: 172.20.0.1